feat: 메인 로그인 페이지 이메일 체크 api연동 및 axios instance 생성
pungdong/DiveInto-mobile-app pull request #115
Opened 2021-05-31 17:13 UTC by kym123123

2021-06-01 14:59 UTC, nightohl requested changes
깔끔하게 잘 짜주셨네요! 리뷰 사항 몇개만 수정요청 드립니다~!

2021-06-01 14:59 UTC, nightohl commented on src/components/WriteReview/Content.tsx
> +  const [textValue, setTextValue] = useState<string>('');
기본 자료형의 경우에는 타입추론을 활용하는 것이 더 깔끔한 것 같습니다!

2021-06-01 14:59 UTC, nightohl commented on src/components/LoginWithEmail/PWInput.tsx
> +        spellCheck={false}
앞으로 있을 입력란들도 자동완성이 오히려 불편할텐데, 이런 옵션들을 미리 적용시켜서 Wrapper 컴포넌트로 만들어서 쓰는 것도 좋을 거 같아요.

안그래도 입력란 바깥 터치 시 키패드가 내려가도록 컨테이너 뷰를 wrapper로 만들 생각이었는데 만드는 김에 textInput도 그렇게 만들어 쓰면 좋을 거 같습니다.

작성 완료하고 스크럼때 공유하겠습니다~!

2021-06-01 14:59 UTC, nightohl commented on src/components/WriteReview/Content.tsx
> +        multiline={true}
멀티라인의 경우에는 특히 return버튼이 줄바꿈 버튼으로 바뀌다보니 키패드가 계속 떠있는 불편함이 있습니다.
터치와 연계시켜서 키패드가 내려가도록 연계하는 것이 중요할 거 같아요!

wrapper view 컴포넌트 제작되면 가장 바깥의 View를 wrapper view로 대체시켜주세요~!

2021-06-01 14:59 UTC, nightohl commented on src/components/WriteReview/StarRatings.tsx
> +const instructorRate = atom<number>({
atom 선언부는 recoil/ 경로 하위로 따로 파일 분리 부탁드립니다!

2021-06-01 14:59 UTC, nightohl commented on src/components/WriteReview/StarRatings.tsx
> +  let stars = [];
참조형 데이터는 할당된 메모리 주소 자체가 변하는게 아닌이상 동일한 객체이며, push pop 등으로 안의 내용이 바뀌더라도 const가 위반되지 않습니다.
`const stars = [];`

2021-06-01 14:59 UTC, nightohl commented on src/components/WriteReview/StarRatings.tsx
> +      <View>
강사, 강의, 장소 세개가 동일한 상태를 사용하는 것으로 보입니다. 별도의 상태로 관리될  필요가 있습니다.

또한 강사, 강의, 장소 모두 동일한 내용이므로, 제목과 상태만 프롭으로 전달받는 재사용 가능한 컴포넌트로 분리할 수 있을 거 같아요!

2021-06-01 14:59 UTC, nightohl commented on src/components/WriteReview/UploadPics.tsx
> +      {isListed && (
업로드 연계되면 undefined인지 아닌지로 검사하면 될 거 같아요!
업로드 라이브러리 오늘 붙여놓겠습니다..!

2021-06-01 14:59 UTC, nightohl commented on src/components/WriteReview/styles.ts
> +const styles = StyleSheet.create({
저도 해보면서 느낀 점인데 styles.ts 파일은 하나로 두되, StylesSheet는 컴포넌트 별로 나눠서 쓰는 것이 수정편집 하기 깔끔한 거 같아요!
컴포넌트에서 쓸 때에는 `import {ExampleComponentStyles as styles} from './styles';` 이런식으로 쓰면 컴포넌트 내에서는 `styles.someTextStyle` 이런식으로 쓰면 됩니다!

2021-06-02 02:00 UTC, nightohl requested changes
이메일 체크 구현 수정 요청사항 있습니다!

2021-06-02 02:00 UTC, nightohl commented on src/components/Login/EmailInput.tsx
> +    checkEmailValidation(text) ? setIsValid(true) : setIsValid(false);
isValid, email, toggleCheckBox, isLoading 등 상태선언은 최상위로 빼주시고, 상태변화와 관련된 함수들은 그 아래에 모아주세요.

상태선언과 이름만 보고서 아래 코드에 어떤 내용들이 있겠구나 짐작도 할 수 있을 뿐더러, 코드 읽을 때 흐름상 맞아야하는데 onTextInput에서 쓰이는 setIsValid에 대한 상태선언이 아래에 있으면 상태선언 부분을 별도로 찾아내려가야 합니다 ㅜ

2021-06-02 02:00 UTC, nightohl commented on src/components/Login/EmailInput.tsx
> +  const [isLoading, setIsLoading] = useRecoilState(isLoadingState);
isLoading을 recoil 상태로 쓰시는 이유가 있으신가요?
로딩 상태를 다른 컴포넌트랑 공유해야하는 경우가 있을까요?

2021-06-02 02:00 UTC, nightohl commented on src/components/Login/EmailInput.tsx
> +      if (checkEmail.data.existed) navigation.navigate('LoginWithEmail');
마찬가지로 화면전환 관련된 부분만이라도 스크린으로 빼는 것이 좋다고 생각합니다.
스크린 컴포넌트만 보고서도 어떤 화면들과 연계되는지를 바로 알 수 있습니다.

2021-06-02 02:00 UTC, nightohl commented on src/components/Login/EmailInput.tsx
> +  useEffect(() => {
textInput에는 setEmail만 있고, 이메일이 바뀔 때마다 onTextInput(email)을 호출하시기 위해서 useEffect를 쓰신 거 같아요.

이메일 입력값이 바뀔때마다 실행되기를 원하시는 거면 setEmail 대신 onTextInput(email)을 바로 textInput의 onChangeText에 넣는게 깔끔할 거 같아요.

2021-06-02 02:00 UTC, nightohl commented on src/components/Login/EmailInput.tsx
> +      ) : (
이거는 어떤 의미로 추가하신 건지 여쭤봐도 될까요?

2021-06-02 02:03 UTC, nightohl commented on src/recoil/ReviewStack.ts
> +export const ratingStarState = atomFamily<number, string>({
별점 보다가 atomFamily로 쓰면 깔끔하겠다 생각했었는데 이미 해두셨네요. 좋습니다!

2021-06-02 08:40 UTC, kym123123 commented
상세한 리뷰 감사합니다. 이런거 처음받아봐요 ㅎㅎ

저렇게 먼저 pr 해놓고 나중에 수정 한 부분 있는데, 그 수정된 부분이랑 말씀해주신거 반영해서 다시 pr 하겠습니다~

2021-06-02 12:58 UTC, kym123123 commented on src/components/Login/EmailInput.tsx
> +  const [isLoading, setIsLoading] = useRecoilState(isLoadingState);
review 스택에서 사용되는 loading은 모두 그 상태값으로 사용하려는 의도로 recoil 상태로 했었습니다

2021-06-02 12:59 UTC, kym123123 commented on src/components/WriteReview/Content.tsx
> +  const [textValue, setTextValue] = useState<string>('');
수정 완료 했습니다.

2021-06-02 13:00 UTC, kym123123 commented on src/components/WriteReview/StarRatings.tsx
> +const instructorRate = atom<number>({
수정 완료 했습니다.

2021-06-02 13:00 UTC, kym123123 commented on src/components/WriteReview/StarRatings.tsx
> +  let stars = [];
수정 완료 했습니다.

2021-06-02 13:00 UTC, kym123123 commented on src/components/WriteReview/StarRatings.tsx
> +      <View>
수정 완료 했습니다.

2021-06-02 13:00 UTC, kym123123 commented on src/components/Login/EmailInput.tsx
> +import instance from '@/src/lib/api/axios';
수정 완료 했습니다.

2021-06-02 13:00 UTC, kym123123 commented on src/components/Login/EmailInput.tsx
> +import { useNavigation } from '@react-navigation/core';
수정 완료 했습니다.

2021-06-02 13:02 UTC, kym123123 commented on src/components/Login/EmailInput.tsx
> +      if (checkEmail.data.existed) navigation.navigate('LoginWithEmail');
수정 완료 했습니다.

2021-06-02 13:14 UTC, kym123123 commented on src/components/Login/EmailInput.tsx
> +  useEffect(() => {
수정완료했습니다~

2021-06-02 13:14 UTC, kym123123 commented on src/components/Login/EmailInput.tsx
> +      ) : (
상태를 생각없이 너무 많이 만들었더니 로직이 이상했었네요 수정완료했습니다~

2021-06-02 13:15 UTC, kym123123 commented on src/recoil/ReviewStack.ts
> +export const ratingStarState = atomFamily<number, string>({
감사합니다

2021-06-05 13:18 UTC, merged