community stack 추가
pungdong/DiveInto-mobile-app pull request #91
Opened 2021-05-24 22:42 UTC by Cho-yunah

- community list 페이지 및 stack 추가
- setPassword 유효성 검사에 특수문자 추가

2021-06-02 02:22 UTC, nightohl requested changes
커뮤니티 목록 수정요청사항 있습니다!

2021-06-02 02:22 UTC, nightohl commented on src/components/Community/CommunityItem.tsx
> +          <TouchableOpacity activeOpacity={0.5} style={styles.commentAndLike}>
댓글개수, 좋아요개수를 컴포넌트로 분리해서 쓰면 코드파악도 잘되고 코드도 깔끔할 거 같아요!

2021-06-02 02:22 UTC, nightohl commented on src/components/Community/CommunityItem.tsx
> +            <View>
작성자-작성일도 하나의 컴포넌트로 분리하면 좋을 거 같습니다!

2021-06-02 02:22 UTC, nightohl commented on src/components/Community/index.tsx
> +  const [contentItem, setContentItem] = useState<ContentItem[]>([]);
오 제네릭 잘 쓰셨네요 좋습니다!

2021-06-02 02:22 UTC, nightohl commented on src/components/Community/index.tsx
> +export type ContentItem = {
타입은 별도 파일로 뺴주시면 좋아요!

2021-06-02 02:22 UTC, nightohl commented on src/components/Community/index.tsx
> +        <View style={styles.tabContainer}>
공유해요, 궁금해요는 `createMaterialTopTabNavigator`로 네비게이터를 따로 만드시는 것이 좋을 거 같아요!

2021-06-02 02:22 UTC, nightohl commented on src/components/Community/style.ts
> +import { getAutomaticTypeDirectiveNames } from 'typescript'
이거는 어떤 의미인가요?

2021-06-02 02:22 UTC, nightohl commented on src/navigators/CommunityStack/index.tsx
> +        <Stack.Screen
Stack안에 Tab을 끼는 형태로 가야할 거 같아요!
커뮤니티 메인 페이지는 `createMaterialTopTabNavigator`로 탭 네비게이터로 수정 부탁드립니다!

2021-06-02 02:22 UTC, nightohl commented on src/screens/CommunityList/index.tsx
> +      <CommunityList />
스크린과 컴포넌트를 나눈 것에 의미를 두기 위해서
스크린에서 api요청을 해서 목록을 상태로 관리하고, 상태개수만큼 컴포넌트를 생성하여 렌더링 하는 것이 좋을 거 같긴 합니다!

2021-06-02 02:27 UTC, nightohl commented on src/components/CommunityMain/AddContentButton.tsx
> +export default function AddContent({ onPress }: { onPress: () => void }) {
스크린 우측 버튼은 `components/navigator/` 하위 경로에 버튼 컴포넌트로 만들어서, 모든 스크린에서 쓸 수 있게 하면 좋을 거 같아요!
만들어뒀던 것으로 기억합니다!

2021-06-02 02:27 UTC, nightohl commented on src/screens/CommunityMain/index.tsx
> +  const onPress = () => navigation.navigate('CommunityMain');
현재 페이지가 `CommunityMain`인데 `onPress` 함수는 어떤 컴포넌트를 위한 것인가요?

2021-06-02 02:33 UTC, nightohl commented on src/components/CommunityMain/CommunityList.tsx
> +      // <FlatList
오 FlatList 미리 대비해두셨네요. 좋습니다!

2021-06-02 02:33 UTC, nightohl commented on src/components/CommunityMain/CommunityMain.tsx
> +        <Suspense fallback={<Text>Loading...</Text>}>
오 서스펜스 활용 좋습니다!

2021-06-02 02:33 UTC, nightohl commented on src/components/CommunityMain/CommunityMain.tsx
> +          <TouchableOpacity>
앞에 커밋에서 말씀드린 부분인데, 탭 네비게이터로 분리해주세요!

2021-06-02 02:50 UTC, nightohl requested changes
수정 요청사항 있습니다!

2021-06-02 02:50 UTC, nightohl commented on src/components/CommunityPosting/EditCompleteButton.tsx
> +export default function EditComplete({ onPress }: { onPress: () => void }) {
마찬가지로 스크린 우측상단 버튼은 `@components/navigator/` 하위에 버튼 컴포넌트로 분리해서 모든 스크린에서 쓸 수 있도록 하는게 좋습니다!
아마 작성해뒀던 걸로 기억해요!

2021-06-02 02:50 UTC, nightohl commented on src/components/CommunityPosting/SelectCategory.tsx
> +import DropDownPicker from 'react-native-dropdown-picker';
드롭다운 다른 라이브러리 쓰다가 바깥 스크린에서 배경색상을 지정하면 드롭다운 컴포넌트가 가려지는 문제가 있어서 안썼던 기억이 있는데, 이거는 그런 문제는 없었나요? 
라이브러리 채택 좋습니다~!

2021-06-02 02:50 UTC, nightohl commented on src/components/CommunityPosting/TitleAndContents.tsx
> +    <View style={styles.inputContainer}>
코드가 다 동일하고 placeholder랑 text style만 다른 경우라서, 별도의 컴포넌트로 분리하면 좋을 거 같아요.
placeholder, testStyle만 프롭으로 전달받도록 분리하면 좋을 거 같습니다.

디자인 통일성을 위해서 wrapper 컴포넌트들을 여러개 빼둘 생각인데 만들어주시면 그대로 wrapper로 뺴두면 될 거 같아요!

2021-06-02 02:50 UTC, nightohl commented on src/components/CommunityPosting/styles.ts
> +export const styles = StyleSheet.create({
저도 하면서 느낀 점인데, 폴더 내부에 컴포넌드들이 많아지는 경우는 스타일도 따로 분리하는 게 관리하기 좋더라구요.
`styles.ts` 파일은 하나로 두되 StyleSheet를 여러개 생성해서 쓰는 게 좋은 거 같아요!

styles.ts에서
`const postingStyles = StyleSheet.create(...)`

화면에서는
`import {postingStyles as styles} from './styles;`
이런식으로 쓰면 컴포넌트 내에서는 `styles.Text` 이런식으로 쓸 수 있습니다!

2021-06-02 02:50 UTC, nightohl commented on src/screens/CommunityMain/index.tsx
> +import { CommunityPostingProps } from '@/src/navigators/CommunityStack/types';
`@navigators/CommunityStack/types`로 사용 부탁드려요!

2021-06-02 02:50 UTC, nightohl commented on src/components/CommunityPosting/CommunityPostingMain.tsx
> +export default function CommunityPostingMain() {
이 부분이 `screens/CommunityMain/index.tsx` 로 가면 딱 좋을 거 같습니다!
컴포넌트들이 조합된 하나의 화면이라서 스크린으로 가는게 좋을 거 같아요

2021-06-02 02:55 UTC, nightohl requested changes

2021-06-02 02:55 UTC, nightohl commented on src/components/CommunityDetail/DetailInfo.tsx
> +       <View style= {styles.buttons}>
수정 삭제 버튼은 별도의 컴포넌트로 빼는게 좋을 거 같습니다.
1. 수정,삭제 버튼을 묶어서 하나의 컴포넌트로 빼셔도 되고, 
2. 형태가 동일하므로 EditButton으로 빼시고 <EditButton 수정 /> <EditButton 삭제 /> 이렇게 쓰셔도 될 거 같아요.
`text`, `style`, `onPress`를 프롭으로 전달받으면 될 거 같네요!

2021-06-03 08:30 UTC, Cho-yunah commented on src/components/Community/index.tsx
> +  const [contentItem, setContentItem] = useState<ContentItem[]>([]);
감사합니다!! :D

2021-06-03 09:21 UTC, Cho-yunah commented on src/components/Community/style.ts
> +import { getAutomaticTypeDirectiveNames } from 'typescript'
잘못 들어갔는데 안지웠나봐요ㅠㅋㅋㅋㅋ 아무의미 없습니다ㅠ

2021-06-05 11:40 UTC, merged